Traceback (most recent call last):
  File "/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/run_launcher.py", line 13, in <module>
    t2d = Telemac2d('/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas', comm=comm, stdout=6)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/t2d.py", line 58, in __init__
    super(Telemac2d, self).__init__("t2d", casfile, user_fortran,
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/api_module.py", line 234, in __init__
    self.cas = TelemacCas(self.casfile, self.dicofile)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 116, in __init__
    self._set_io_files()
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 377, in _set_io_files
    raise TelemacException(
utils.exceptions.TelemacException: In /home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas missing file for BOUNDARY CONDITIONS FILE:
 geo_donau.cli
Traceback (most recent call last):
  File "/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/run_launcher.py", line 13, in <module>
    t2d = Telemac2d('/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas', comm=comm, stdout=6)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/t2d.py", line 58, in __init__
    super(Telemac2d, self).__init__("t2d", casfile, user_fortran,
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/api_module.py", line 234, in __init__
    self.cas = TelemacCas(self.casfile, self.dicofile)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 116, in __init__
    self._set_io_files()
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 377, in _set_io_files
    raise TelemacException(
utils.exceptions.TelemacException: In /home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas missing file for BOUNDARY CONDITIONS FILE:
 geo_donau.cli
Traceback (most recent call last):
  File "/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/run_launcher.py", line 13, in <module>
    t2d = Telemac2d('/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas', comm=comm, stdout=6)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/t2d.py", line 58, in __init__
    super(Telemac2d, self).__init__("t2d", casfile, user_fortran,
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/api_module.py", line 234, in __init__
    self.cas = TelemacCas(self.casfile, self.dicofile)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 116, in __init__
    self._set_io_files()
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 377, in _set_io_files
    raise TelemacException(
utils.exceptions.TelemacException: In /home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas missing file for BOUNDARY CONDITIONS FILE:
 geo_donau.cli
Traceback (most recent call last):
  File "/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/run_launcher.py", line 13, in <module>
    t2d = Telemac2d('/home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas', comm=comm, stdout=6)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/t2d.py", line 58, in __init__
    super(Telemac2d, self).__init__("t2d", casfile, user_fortran,
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/telapy/api/api_module.py", line 234, in __init__
    self.cas = TelemacCas(self.casfile, self.dicofile)
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 116, in __init__
    self._set_io_files()
  File "/home/schwindt/Software/telemac/v8p4r0/scripts/python3/execution/telemac_cas.py", line 377, in _set_io_files
    raise TelemacException(
utils.exceptions.TelemacException: In /home/schwindt/Software/telemac/v8p4r0/examples/telemac2d/donau/t2d_donau.cas missing file for BOUNDARY CONDITIONS FILE:
 geo_donau.cli
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40908,1],0]
  Exit code:    1
--------------------------------------------------------------------------
